### Autenticacion incorrecta
POST http://localhost:7777/api/v1/auth/
Content-Type: application/json
Accept: application/json

{
  "email": "lramirez",
  "password": "ABCabc123"
}

### Autenticacion correcta
POST http://192.168.1.40:7777/api/v1/auth/
Content-Type: application/json
Accept: application/json

{
  "email": "jperez@gmail.com",
  "password": "ABCabc123"
}

### Autenticacion con valores vacios
POST http://localhost:7777/api/v1/auth/
Content-Type: application/json
Accept: application/json

{
}
################# Consultar usuario

GET http://localhost:7777/api/v1/person/
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqcGVyZXpAZ21haWwuY29tIiwicm9sZXMiOlsiQVBMSUNBUl9UUkFCQUpPIl0sImlzcyI6InVjYiIsInJlZnJlc2giOmZhbHNlLCJleHAiOjE2Njk5MDUxMDF9.mMeOXFMvaYplxi3E0uwWRdTt72-nDe1nouqjWZvP0pI